name: testing

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    env:
      PYTORCH_VERSION: "1.12.0"

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # https://github.com/actions/cache/blob/main/examples.md#python---pip
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python-version }}-pip-

    - name: Install w/ PyTorch ${{ env.PYTORCH_VERSION }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install torch==${{ env.PYTORCH_VERSION }} --extra-index-url https://download.pytorch.org/whl/cpu
        python -m pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-${{ env.PYTORCH_VERSION }}+cpu.html
        python -m pip install -e .[dev,docs]

    - name: Test with pytest
      run: |
        python -m pytest -v --color=yes tests/

    - name: Build docs
      if: matrix.python-version == '3.9'
      run: |
        sudo apt-get install -y pandoc
        sphinx-build docs docs_build

    - name: Deploy docs at main branch
      if: ${{ matrix.python-version == '3.9' && github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./docs_build
